### ISSUE TITLE
No mention of savegame compatibility

### ISSUE THREAD

**Issue by Darxo** [OberKnirps/Twitch-Brothers#2]
By looking at the de-/serialization in https://github.com/OberKnirps/Twitch-Brothers/blob/main/scripts/mod_twitch_brothers/twitch_name_pool.nut it seems like your mod can't be added to existing playthroughs and can't be removed from existing playthroughs. But I don't see this mentioned in the readme.

I suggest you add information about whether one can add- or remove the mod from savegames.

**Comment by OberKnirps** [comment]
Thanks for the tip. It can actually added to existing savegames because the deserialization safeguard is higher up in the chain. But I still added a compatibility section to github b2bc898 and nexus
